import { Inter } from 'next/font/google'
import './globals.css'
import { GoogleOAuthProvider } from '@react-oauth/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SpaceX Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='app'>
    <GoogleOAuthProvider clientId='633450706728-a6dqo5ojek6brgj4obajhasumkq82331.apps.googleusercontent.com'>
   
      <body suppressHydrationWarning={true} className={inter.className}><div className='app'>{children}</div></body>
      </GoogleOAuthProvider>
    </html>
    
  )
}
